name: Local Config
version: 1.0.0
schema: v1

models:
  - name: ai-env
    provider: openai
    model: ai-env
    apiBase: http://127.0.0.1:9000/v1
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - embed
      - rerank
    capabilities:
      - tool_use
      - image_input
